### PR TITLE
Table <=> HashMap and fix for entrySet()

### PR DESCRIPTION
**Pull request by Turakar**
The conversion is implicit (added functionality to l2jType() and j2lType()) and recursive. As the peripheral API uses l2jType, it also supports tables now (yay!).

I also found a bug in the entrySet() method, it skipped the first element. Fix is in the PR.

### CODE REVIEW

**Comment by Turakar** [comment]
Changed that.

**Comment by ElvishJerricco** [comment]
So is this good now @Yevano?

**Comment by Yevano** [comment]
It's been a real long time since I've looked at this. If nothing has changed since then, then I'm fine with this being pulled.

**Comment by Turakar** [comment]
I moved out the HashMap <=> Table Conversion and put it into separate methods. That's all.

**Comment by ElvishJerricco** [comment]
I think it's good. Merging.

**Pull request merged**
