### PR TITLE
Removed Oracle files

### PR DESCRIPTION
**Pull request by gamemanj**
2 files, I've noticed, were apparently from the Oracle JVM.
One was under the GPL, which since the release bundles a .jar is a pretty big problem, and the other is marked with some arcane header.
I've deleted one(SuppressWarnings.java) and rewritten the other(InputStream.java).
(EDIT: This is a bit out of date-I added IndexOutOfBounds checks for both InputStream and OutputStream into my file-io development branch. Should File IO be merged into master?)

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Shouldn't we just need to use a GPL license, with s copy of oracles license included, to re-release GPL licensed code? I feel that is the better solution. I also don't understand why you would entirely remove SurpressWarning

**Comment by oldmud0** [comment]
Are you saying we should change our MIT license to GPL?

**Comment by ElvishJerricco** [comment]
Would that be terribly bad?

**Comment by oldmud0** [comment]
Yeah

**Comment by gamemanj** [comment]
...SuppressWarnings.java wasn't of a very high priority, and it looked like the only real implementation would end up looking exactly like Oracle's. Which would of course lead to problems.
So I decided to remove it, to avoid problems.
If it needs re-implementation, feel free to re-implement it.
I'm just trying to avoid any potential problems.

**Comment by ElvishJerricco** [comment]
I feel we haven't reached a solution here. @Yevano what do you think?

**Comment by Yevano** [comment]
My original idea was to have everything working so that most of the original Java library would work. The way I see it, we have the following options:
1. Change the license to be compatible with Java's sources and continue using them where possible.
2. Recode all the Java library classes we need.
3. Require Java library classes to be present in binary form and pack them into rt.jar.

I like option 3 the best and here's why. Option 1 is pretty nice since it requires the least amount of work on our part, but there's a problem. It implies that we just copy code over and over into our repo when it already exists elsewhere. Option 2 seems to be the direction @gamemanj was going with his changes, but I don't like this idea. Why would we recode it we already have the code? Maybe if we made it "look" a little different it would be okay? Hmm, we could just take out the license comment and replace it with... ohhhh nooo, now we done messed up.

I'll explain option 3 now. What we could do is have a registry of which classes we import from the real Java standard library, and create a tool which would fetch them for when we do compilation of the custom rt.jar and also to pack them into the custom rt.jar for the end-user. This has a couple practical implications. First, there would be no sources or binaries from the JDK bundled in our releases. Second, it is then up to the user to run a provided script to fetch classes from the JDK before using JVML in-game.

**Comment by gamemanj** [comment]
Option 3 means we end up having to compile a custom rt.jar anyway, so that needs to be .gitignore'd for legal reasons. Which in itself means we either need a better installer...or we need to place burdens on the user. Oh, and people wanting to work on the code.

If the JVM was set up to allow "look in our jar file first, then in another one" we could do this without needing to build anything with Oracle(or GNU Classpath) code in it or duplicating much code.

The question then rests on internal interfaces in stuff we DO have to override for any given reason.
It's probable that my implementation of FileIO isn't the only one putting stuff in FileDescriptor, and unfortunately internal interfaces tend to change.(Yep, looked it up: there's a internal interface in FileDescriptor. It's not being used as a point to connect a raw interface to a nice user-friendly one like my implementation, though.)

This problem exists with normal Option 3 anyway.

I recommend using GNU Classpath with Option 1, or continuing as we are with the Oracle code removed.(Option 2)
We might want to use jatovm/classpath 's mirror to avoid duplicating code-have the build script apply a set of patches + additions(which we'd of course GPL).
The GPL-ism should be contained within rt.jar since we're not actually linking anything to it.
Course, stuff will probably need restructuring a bit. That's to be expected.
Plus, FileDescriptor generally works on the basis of a Unix-like "integer==FD" system, so there's something we'll have to work around.
But it'll definitely be the most _compatible_ yet (hopefully, please double-check the GPL _with Classpath exception_) _legal_ solution.

**Comment by ElvishJerricco** [comment]
I'm not a fan of doing all this work-around for Java's license's sake. Writing a Java runtime is huge, and we don't want to have yet another layer of complexity and difficulty in using oracle code. We have to make this easy on ourselves. So we have to either just change the license, or avoid licensing issues altogether by never using Oracle code. Never using Oracle code just sounds like a pain. Why reinvent the wheel and write an entire java runtime from scratch, when we can save ourselves loads of work by using pre-existing code?

**Comment by ElvishJerricco** [comment]
Besides, how on earth are we going to implement things that are so unbelievably trivial, like SuppressWarnings, without getting into a horrible legal grey area? Which btw, SuppressWarnings really shouldn't have been removed. You say it "wasn't of a very high priority," but it's something absurdly trivial that helps users out.

These licensing issues are preventing easy features that would help users significantly.

**Comment by gamemanj** [comment]
As I already wrote: Option 1 using GNU Classpath, using jatovm's repository (and a code patcher if need be).

**Comment by ElvishJerricco** [comment]
@Yevano what do you think of GNU Classpath? I think it sounds like a good enough solution.

**Comment by Yevano** [comment]
Sounds like a fine solution. It's more robust and less complicated than the one's I came up with anyway.

**Pull request closed without merging**
